# -*- coding: utf-8 -*-
"""CommunityInteractionData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vPoUGilxsMNqqBfDYx1vWBK8Bd0YGEn5
"""

import pandas as pd

# Load the dataset
file_path = "/content/frontend_beginners_QA_dataset.csv"
dataset = pd.read_csv(file_path)

# Check the dataset
print(dataset.head())

!pip install nltk scikit-learn

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
import string

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab') # Download the missing punkt_tab data

# Preprocessing function
def preprocess_text(text):
    text = text.lower()  # Lowercase
    text = text.translate(str.maketrans('', '', string.punctuation))  # Remove punctuation
    tokens = word_tokenize(text)  # Tokenize
    stop_words = set(stopwords.words('english'))  # Remove stopwords
    tokens = [word for word in tokens if word not in stop_words]
    lemmatizer = WordNetLemmatizer()  # Lemmatize
    tokens = [lemmatizer.lemmatize(word) for word in tokens]
    return ' '.join(tokens)

# Apply to Question and Answer columns
dataset['Processed_Question'] = dataset['Question'].apply(preprocess_text)
dataset['Processed_Answer'] = dataset['Answer'].apply(preprocess_text)

# Save preprocessed dataset
dataset.to_csv("preprocessed_dataset.csv", index=False)
print("Preprocessing complete and saved.")

"""**Train the Classification Model**

Random Forest for Categorizing Questions
"""

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

# Convert text data into numeric vectors
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(dataset['Processed_Question'])
y = dataset['Category']  # Ensure your dataset has this column

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Train and evaluate the Random Forest model"""

# Train Random Forest
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

# Evaluate the model
y_pred = classifier.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

import pickle

with open("classification_model.pkl", "wb") as f:
    pickle.dump(classifier, f)
with open("vectorizer.pkl", "wb") as f:
    pickle.dump(vectorizer, f)

"""**Train the Recommendation Model**"""

print(dataset.columns)

from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# Assuming 'Question_ID' is the intended column for user identifiers
interaction_data = pd.pivot_table(
    dataset,
    index='Question ID',  # Replace 'User' with the correct column name
    columns='Category',  # Replace 'Category' with the column indicating topics
    values='Question',  # Replace 'User Rating' with the correct column for ratings
    fill_value=0,
    # Instead of 'first', use a numerical aggregation like 'count' if you want
    # to base similarity on the number of questions in each category for each ID.
    # If you have a relevance score, use that column for 'values' instead of 'Question'.
    aggfunc='count'
)

# Convert the interaction data to a numerical format
# This handles potential string values introduced by the 'first' aggregation
interaction_data_numeric = interaction_data.apply(pd.to_numeric, errors='coerce').fillna(0)

# Calculate cosine similarity on the numeric data
similarity_matrix = cosine_similarity(interaction_data_numeric)

"""Define a recommendation function"""

def recommend_peers(user_id, num_recommendations=3):
    user_idx = interaction_data.index.get_loc(user_id)
    similar_users = list(enumerate(similarity_matrix[user_idx]))
    similar_users = sorted(similar_users, key=lambda x: x[1], reverse=True)[1:num_recommendations+1]
    return [interaction_data.index[i[0]] for i in similar_users]

# Example: Recommend peers for user 101
print(recommend_peers(user_id=101))

"""**Integrate Models**"""

def find_peers(query, user_id):
    # Preprocess the query
    processed_query = preprocess_text(query)

    # Predict topic using classification model
    query_vector = vectorizer.transform([processed_query])
    predicted_topic = classifier.predict(query_vector)[0]

    # Recommend peers
    recommended_peers = recommend_peers(user_id)
    return predicted_topic, recommended_peers

# Example usage
query = "How do I style a button in React?"
user_id = 101
topic, peers = find_peers(query, user_id)
print(f"Topic: {topic}, Recommended Peers: {peers}")

"""**Testing the System**"""

from sklearn.model_selection import train_test_split

# Split the dataset
train_data, test_data = train_test_split(dataset, test_size=0.2, random_state=42)

"""Test the Classification Model"""

# Example: Predict category for a test question
test_questions = test_data['Question']
true_categories = test_data['Category']

# Preprocess test questions (similar to training data preprocessing)
preprocessed_questions = test_questions.apply(preprocess_text)

# Predict categories
predicted_categories = classifier.predict(vectorizer.transform(preprocessed_questions))

# Evaluate accuracy
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(true_categories, predicted_categories)
print(f"Classification Model Accuracy: {accuracy * 100:.2f}%")

"""Test the Recommendation Model"""

# Example: Test recommendation for a specific question category
test_question = "How do I center a div in CSS?"  # Example query
# Use the classifier to predict the category, not recommend_peers
predicted_category = classifier.predict(vectorizer.transform([preprocess_text(test_question)]))[0]

# Find peers with expertise in the predicted category
recommended_peers = recommend_peers(user_id=101, num_recommendations=3)  # Pass user_id and num_recommendations

print(f"Recommended peers for '{predicted_category}': {recommended_peers}")

def recommend_peers(category, similarity_matrix, user_topic_interactions, top_n=5):
    # Find users who interacted with the category
    category_idx = user_topic_interactions.columns.get_loc(category)
    similar_users = similarity_matrix[category_idx].argsort()[::-1][:top_n]
    return user_topic_interactions.index[similar_users]